services:
  - name: cnc-svg-generator
    type: web
    runtime: go
    buildCommand: 'go build -o app .'
    # startCommand: './app'
    startCommand: './cmd/server/main.go'
    envVars:
      - key: PORT
        value: 8080
