# fly.toml app configuration file generated for cnc-svg-generator on 2025-01-14T01:16:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cnc-svg-generator'
primary_region = 'den'

[build]
  [build.args]
    GO_VERSION = '1.23.4'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
